<?php
$donors100 = array(
	array("x","","","O","The Barrington Foundation Inc. ",""),
	array("x","","","O","James M. Clark '76 ",""),
	array("x","","","O","Emily H. Fisher P '83",""),
	array("","","","","The John S. and Cynthia L. Reed Foundation ",""),
	array("","","","O","The Sealark Foundation ",""),
	array("","","","","Scott Shenker and Mary Ruth Quinn P '09 & '11","In honor of Sam Ruhmkorff and Asma Abbas"));
	
$donors2599 = array(
	array("","","","","Anonymous",""),
	array("x","","","O","Margaret Kendrick Blodgett Foundation ",""),
	array("x","","","O","Stuart Breslow and Anne Miller-Breslow P '07","In honor of Philip S. Breslow '07"),
	array("","","","","David Brown ",""),
	array("x","","","O","John K. Hall ",""),
	array("x","","","O","Murray and Patti Liebowitz ",""),
	array("x","","","O","Alvin '92 and Chelsey Loshak ",""),
	array("","","","","Riversville Foundation",""),
	array("x","","","O","The Spingold Foundation Inc. ",""),
	array("","","","","The Stewart Foundation ","In honor of Emily H. Fisher's birthday"));
	
$donors1524 = array(
	array("","","","O","Anonymous",""),
	array("x","","","","Zachary '85 and Allison Julius ",""));
	
$donors1014 = array(
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous",""),
	array("","","","","Catherine Fisher '83 ",""),
	array("x","A","","","Paul W. Goldschmidt '84 ",""),
	array("","","","","Nita Ing '71 ",""),
	array("x","","","","Bernie F. Rodgers, Jr.","In memory of Jane Rodgers"),
	array("x","","","O","Sally E. Unger '73 ","In honor of Rodney Christopher '86"),
	array("","","","","Miriam Weizenbaum '76 ",""));

$donors59 = array(
	array("x","","","O","Susan Beckerman P '96 & '99",""),
	array("x","A","","O","Christopher '86 and Cordelia '86 Derhammer-Hill ",""),
	array("x","","","","Jesse A. Fecker '92 ",""),
	array("x","","","O","Julia and Robert Greifeld P '05",""),
	array("","","","","Peter Laipson and Alison Lobron ","In honor of Emily H. Fisher's extraordinary tenure as Chair of the Board of Overseers"),
	array("","","","","Zane Lazer '86 and Margaret Heath Lazer '82",""),
	array("","","","O","Morgan Stanley Cybergrants, Inc",""),
	array("x","","","","Glenn M. Peacock '83 and Joel Palefsky ","In memory of Dottie-Lou Brokaw"),
	array("","","","","John and Mary Lynn Pergantis P '12","In memory of Alice Nichols Karelas"),
	array("","","","","Karen Pessione '82 ",""),
	array("x","","","","Jeffrey Resnick '80 ","In memory of Florence Resnick"),
	array("","","","","Rose and Kiernan, Inc.",""),
	array("","","","","Joanna Seltzer '99, Henry Seltzer '02, and Richard and Kim Seltzer","In honor of Elvira and Gilbert Isaacs"),
	array("","","","","Sabrena A. Silver '85 ",""),
	array("x","","","","Patricia J.S. Simpson P '86",""),
	array("","","","","Sprague Foundation, Inc.",""),
	array("x","","","","Larry Swales and Dr. Ya-Hui Laurie Pan P '00","In honor of Dr. Stephanie '00 and Frank Swales Scalambrino"),
	array("x","","","","Judith and Ba Win P '90, '91 & '92","In honor of Emily H. Fisher"));

$donors14 = array(
	array("","","","","Lori and Dean Adams P '12",""),
	array("x","","","O","Loren AliKhan '99 ",""),
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous",""),
	array("","","","","Jane Armstrong P '96","In honor of Hendrik Doorn '96"),
	array("","","","","Samir Arora '02 ",""),
	array("","","","","Adam P. Bartos '70 ",""),
	array("","","","","Maryana Bhak '80 and Jong Bhak ","In honor of Margaret Lazer '82"),
	array("x","","","","Jill B. Blanchard '90 ","In memory of Galen Gibson '90"),
	array("","","","","Lee and Jacki Breisacher P '08",""),
	array("","","","","Mellena Bridges and Gregory Curry P '08","In honor of Hannah Bridges-Curry '08"),
	array("x","A","","","Keith '80 and Penny '81 Brierley-Bowers P '08 & '12",""),
	array("","","","","Sandra Brinkert and Lynn Brown P '08",""),
	array("","","","","David Byrd '78 and Ella Brice ",""),
	array("","","","","David Castro '73 ","In memory of Dr. Raymond E. Castro"),
	array("","","","","Chartwells Educational Dining Services",""),
	array("x","","","","Abe '00 and Amelie Chu ",""),
	array("","","","","Christopher '92 and Rhonda '94 Colombo ",""),
	array("x","","","","Meriweather Clark-Connors '76 and Cathy Ingram ","In memory of Faye Polner '76 and in honor of Emily H. Fisher"),
	array("x","","","","Charles and Sara Coe P '97","In honor of Elizabeth Coe '97"),
	array("","","","","Lisa David and Ernest Berger P '08",""),
	array("x","","","","M. Leslie Davidson ","In honor of Emily H. Fisher"),
	array("","","","","Eric L. and Patricia B. Decker P '93",""),
	array("","","","","Deloitte Foundation ",""),
	array("","","","","Chloe Demrovsky '01 ","In memory of Tadd Gero '03"),
	array("","","","","Stephanie Denzel '99 ",""),
	array("","","","","Kenneth Deregt ",""),
	array("","","","","Harvey and Scarlet Edber P '06",""),
	array("x","","","","ExxonMobil Foundation ",""),
	array("","","","","Jennifer Fan '99 ",""),
	array("","","","","Sigmund Friedman and Nancy Grossman P '02","In honor of Kathryn G. Friedman '02"),
	array("","","","","Dr. Harold Gotthelf P '84 ",""),
	array("","","P","","Robert and Joy Gess P '10",""),
	array("x","","","","Christopher M. Gittins '83 ","In memory of Leslie R. Sander '83"),
	array("x","","","","Johnathan and Marjorie Glass P '08",""),
	array("","","","","Gabby Glemann '99 and Paul Reinitz ",""),
	array("x","","","","Jesse Glick '89 and Ali Mahood '90","In honor of Leutitia Swayze Mahood"),
	array("","","","","Geoffrey M. Glick '81 and Marina Daiman ","In honor of John Paskus"),
	array("","","P","","Michelle Goodwin and Gregory Schaffer P '12",""),
	array("","","","","Anita Gould '80 and Richard Snyder ",""),
	array("x","","","","Kaye and Bob Graves ",""),
	array("","","","","Gregory Greifeld '05 ",""),
	array("","","","","Samantha Grillo '86 ",""),
	array("","","","","Ethan and Beth Haskel P '03",""),
	array("x","","","","The Horbach Fund ",""),
	array("x","","","","Louise Rogow Howard '85",""),
	array("x","","","","Rebecca Hughson Leise '71 ",""),
	array("","","","","Joan and Jim Hunter P '04",""),
	array("","","","","Maryan and Sunny Kang P '09, '10 & '12","In honor of Taylor '09, Mia '10 and Elliot '12 Kang, our children"),
	array("","","","","Alec Krikava and Marne Keller-Krikava P '12",""),
	array("","","","","Alison Larkin ","In honor of the Berkshire Festival of Women Writers"),
	array("","","","","Youngro Lee '00 ",""),
	array("","","","","Maggie Leonard '78 and John Humphries ","In honor of all fellow alumni. What an amazing group of people."),
	array("","","","","Mark and Katie Levine ",""),
	array("","","","","Joshua Levy and Pam Magnuson P '10",""),
	array("x","","","","Ian and Mary MacKinnon P '03","In honor of Kelley MacKinnon '03"),
	array("","","","","Susan A. Manning '72 ",""),
	array("","","","","Todd A. Maugans '77 ",""),
	array("","","","","Adrienne Maynard '89 ",""),
	array("","","","","Coleman '98 and Tamara Mehta ",""),
	array("x","","","","Richard and Lynn Melnick P '08","In honor of Annabelle Coote '86 and Miriam Melnick '08"),
	array("x","","","","Microsoft Matching Gifts Program ",""),
	array("","","","","Brian Mikesell and John Weinstein ","In honor of Emily H. Fisher"),
	array("","","","","Miller-Pomerantz Insurance and Financial Services","In honor of Stuart Breslow and Anne Miller-Breslow"),
	array("","","","","Maneesh Modi '94 ",""),
	array("","","","","Rich Montone and Erika Nelson ",""),
	array("","","","","David R. Myers and Susan Cooper ","In honor of Emily H. Fisher"),
	array("","","","","Horace '71 and Betsy Nash P '08",""),
	array("","","","","Thomas and Fee O'Brien P '02",""),
	array("x","","","","Osher Institute for Lifetime Learning ",""),
	array("","","","","Robert Phillips '70 and David Lepore ",""),
	array("x","","","","Quality Printing Company, Inc. ",""),
	array("x","","","","Elizabeth H. Rader '81 ",""),
	array("x","","","","Elizabeth Richardson ",""),
	array("","","","","Edward Roske '90 ",""),
	array("","","","","Susan Roth and Leslie Birenbaum ","In memory of Philip Roth, grandfather of Michael Birenbaum '91"),
	array("","","","","Bruce '81 and Danna Schoenberg ",""),
	array("","","","","George Sells P '10",""),
	array("x","","","","Alexandra Shandell '00 ",""),
	array("","","","","Elise Shapiro ",""),
	array("x","","","","Adam Shostack '88 and Teresa Barcus ",""),
	array("x","","","","Otto and Dorothy Solbrig P '84",""),
	array("x","","","","Judge Morris and Ronnie Stern P '87","In memory of Ben Stern '87"),
	array("","","","","Jeannette and Arthur Taylor ","In honor of Emily H. Fisher"),
	array("","","","","James Teeple '74 ",""),
	array("","","","","Liz Wall '82 and Deb Smucker ","In memory of Edward and Frances Wall"),
	array("x","","","","Arthur Watson '98 ",""),
	array("","","","","Jacqueline A. Wilson P '89",""));
$donors59 = array( 
	array("","","","","James Adler P '12",""),
	array("","","","","Russell Anderson and Daniel Karslake ",""),
	array("x","A","","","Catya Belfer '88 ",""),
	array("","","","","Berkshire Taconic Community Foundation ",""),
	array("x","","","","Joel Bernanke '00 and Elise Kent Bernanke '00 ",""),
	array("x","","","","Scott S. Blake '88 and Liz Rettenmaier ",""),
	array("","","","","Thomas Borkowski P '01, 04 & '07",""),
	array("","","","","Debra Brendal P '11","In honor of Jake Lederman '11"),
	array("x","","","","Cherrylynn and Ethan Burris ","In memory of Noah White Burris '97"),
	array("","","","","Megan Case '92 ",""),
	array("","","","","Veronica Chambers '87 and Jason Clampet ",""),
	array("x","","","","Debbie Cibelli '71 ","In memory of M. Peter Burke '71"),
	array("x","","","","Lucy P. Clark '66 ",""),
	array("","","","","Mark Clifford '74 ",""),
	array("x","","","","Michal Zivan Coffey '95 and Tim Coffey '95 ",""),
	array("x","","","","David Corcoran and Karrie Olick P '05",""),
	array("","","","O","Joan Countryman ",""),
	array("","","","","Raymon Darling P '96","In honor of Aaron E. Darling, PhD '96"),
	array("","","","","Diana Dinh '03 ",""),
	array("","","","","David A. Epstein '95 ","In honor of Peter Cocks and Jim Monsonis"),
	array("x","","","","Deirdre M. Farley '69 ",""),
	array("","","","","Valerie K. Ferrier '94 ",""),
	array("x","","","","Bean '90 and Dan Gilsdorf ","In honor of Hal Holladay"),
	array("x","","","","Laura and William Glasgall P '01",""),
	array("","","","","Kenan Godfrey '92 ",""),
	array("","","","","David Goldstein '86 ",""),
	array("","","","","Andrea Hanna '92 ",""),
	array("x","","","","Nancy S. Hardin P '97","In memory of Noah White Burris '97"),
	array("","","","","Kyle Haver '73 and Susan Goetz Haver ",""),
	array("","","","","Eliza R. Hewat '66 ",""),
	array("","","","","Deborah Hutchison ",""),
	array("x","","","","John '70 and Ann Jacobs ",""),
	array("","","","","John Wiley & Sons, Inc. ",""),
	array("","","","","Johnson & Johnson Family of Companies ",""),
	array("","A","","","Kaki Notestine Kasdorf '93 and Jason F. Kasdorf ",""),
	array("x","","","","Nancy K. Kim P '93",""),
	array("x","","","","Michael Belanger and Ellen Kisslinger P '06","In honor of Rachel Belanger '06"),
	array("","","","","Ellen Kreger Matheson '70 and David Matheson ",""),
	array("x","","","","Anne M. Laughlin '98 ",""),
	array("","","","","Mark Lazer and Mary Spalding P '09 & '11","In honor of Fiona '09 and Lucien '11 Lazar"),
	array("x","","","","Joseph Little '91 and Michiko Yamori ","In honor of Tyler and Harrison Yamori-Little"),
	array("","","","","Chen Liu and Jingchun Wang P '01",""),
	array("","","","","Eleanor Lord ",""),
	array("x","","","","David and Susan Miller P '86",""),
	array("","","","","Margaret Moench '70 and Ira Mellman ",""),
	array("","","","","Christine Terrell Murphy '00 ",""),
	array("","","","","Francisca Oyogoa ",""),
	array("x","","","","Eli Pariser '96 ",""),
	array("","","","","Colleen and James Patell P '03","In honor of Teagan Patell '03"),
	array("","","","","Jim Poe '94 and Susanne Grabowski '94 ","In memory of August Clement Poe"),
	array("","","","","Carol Preisig P '11","In memory of David Preisig and in honor of Charles Preisig"),
	array("","","","","Soyok Quan '92 ",""),
	array("","","","","John and Lynn Rathgeber P '09",""),
	array("","","","","Eric Allix Rogers '01 ","In honor of David Lovely '96 and Jim Lai"),
	array("","","","","Sherri Samuels P'12",""),
	array("","","","","Jim and Diane Schwab P '09","In honor of the Language Department at Simon's Rock"),
	array("","","","","Brooke Skinner '97 ",""),
	array("","","","","Stephen Smith '70 ","In memory of Elizabeth Hall"),
	array("x","","","","Robert and Andrea Solomon P '08",""),
	array("","","","","Richard and Anne Steiner P '12",""),
	array("","","","","Karl Stine '75 ",""),
	array("x","","","","Allyson A. Till '84 ",""),
	array("","","","","Vanguard Charitable Endowment Program ",""),
	array("x","","","","Baird and Joan Whitlock P '72",""),
	array("","","","","Wes and Louise Young P '98",""));
$donors250499 = array(
	array("","","","","Henry Alford '80 ",""),
	array("","","","","Barbara Andrews and John Leonard P '11","In honor of Joseph A. Leonard '11"),
	array("x","","","","Anonymous",""),
	array("","","","","Arch Insurance Company ",""),
	array("x","","","","Thomas and Barbara Armstrong P '99",""),
	array("x","","","","Ruth Ballenzweig '99 ",""),
	array("","","","","Benny and Barbara Barak P '04","In honor of Nancy Yanoshak"),
	array("","","","","Stephanie Barefield '06 ",""),
	array("","","","","Julia M. Bauder '97 ",""),
	array("x","A","","","Jochai Ben-Avie '06 ",""),
	array("x","","","","Carlos and Jesusa Benedicto P '01","In honor of Camilla Benedicto Pimentel '01"),
	array("x","","","","Gail Berneike and Don Bernier ","In memory of Jane Rodgers"),
	array("","","","","Steve Bohrer ",""),
	array("","","","","Nancy Bonvillain ",""),
	array("","","","","Sue and Joseph Browdy ",""),
	array("","","","","Susan and Jack Cobetto P '09",""),
	array("x","","","","Barbara and Rodgin Cohen P '98","In honor of Sara Cohen '98"),
	array("x","","","","Valerie Collura '84 ",""),
	array("","","","","Kathrina De Witt Yost '66 ",""),
	array("","","","","Susan Di Biase P '92",""),
	array("","","","","Pauline '06 and Emmanuel Dongala P '98 & '01",""),
	array("","","","","Ronald and Janice Flaugher P '78",""),
	array("","","","","Larry Gage and Karen Forbes P '09",""),
	array("","","","","Ann Burchfield '04 and Laszlo Frazer '05 ",""),
	array("","","","","Suzy Garfinkle P '08","In honor of Joelle Chevrier '08"),
	array("","","","","Kristin Giantris ",""),
	array("x","","","","Heather Godwin Jones '81 ",""),
	array("x","","","","Judith Gubner Terry '66 and Patrick Terry ","In memory of Dr. Richard Gubner"),
	array("","","","","Khin Khin Gyi '99 ","In Honor of Emily H. Fisher"),
	array("","","","","Louise and Arthur Hillman ","In honor of Emily H. Fisher and Rodney Christopher '86"),
	array("","","","O","Dana and Kathryn Hiscock ",""),
	array("","","","","Christine Hobbie and Neil Brander ",""),
	array("","","","","Jennifer Howland '67 ",""),
	array("","","","","Michael Jefferson and Pamela Augustine-Jefferson P '12","In honor of diversity"),
	array("","","","","The J.P. Morgan Chase Foundation ",""),
	array("","","","","Terry Kaelber '71 and David Buckel ",""),
	array("","","","","Sarah Gould Kagan '75 and Stewart Kagan ",""),
	array("x","A","","","Audrey Kalman '77 ","In memory of Eileen Handelman"),
	array("","","","","Onkar Kapoor '00 ",""),
	array("","","","","Kim Kastens and Dale Chayes P '08",""),
	array("x","","","","Suzanne Klimek '79 ","In honor of Patti and Murray Liebowitz"),
	array("","","","","Dmitry Kondrashov '92 ",""),
	array("","","","","Jan Krause Greene ",""),
	array("x","","","","Michael Lawrence '98 ",""),
	array("","","","","Drew Levin '06 ",""),
	array("x","","","","Sara Lolar '89 ",""),
	array("x","","","","David Lovely '96 and James Lai ",""),
	array("","","","","Edward and Judith Lund P '84",""),
	array("","","","","Michael and Louise Malakoff P '96",""),
	array("","","","","Adam Man '86 ",""),
	array("","","","","Patricia Marcella ",""),
	array("","A","","","Harry Marker '05 ",""),
	array("","","","","Charles McKenrick '02 ",""),
	array("x","","","O","John H.V. McWhorter '81 ",""),
	array("","","","","Merck Partnership For Giving ",""),
	array("","","","","Leila and Bruce Miller ",""),
	array("","","","","Max Miller '90 and Sophia Klatzker ",""),
	array("","","","","James A. Monsonis and Lenore Gensburg '78 ","In memory of Leslie R. Sander '83"),
	array("","","","","Charles Montgomery '89 ","In memory of Ñacuñán Sáez"),
	array("x","","","","Elizabeth M. Morss '78 ",""),
	array("","","","","Marshal Newrock '91 ",""),
	array("","","","","Anne O'Dwyer ",""),
	array("","","","","Paige and John Orloff ",""),
	array("","","","","Alison Overseth ","In honor of Rodney Christopher '86"),
	array("x","","","","Sarah J. Parady '99 ","In honor of Barbara Resnik and Wendy Shifrin"),
	array("","","","","Stephen and Deborah Paruolo P '09",""),
	array("","","","","Julie and Christopher Petr P '12","In memory of Gertrude Petr"),
	array("x","","","","Carrie Richards '93 ",""),
	array("x","","","","Robert Richards '80 ","In honor of John Marsella '80"),
	array("","","","","Kevin Ritchie '85 ","In memory of Leslie R. Sander '83"),
	array("","","","","Tim and Liz Rodgers ","In memory of Jane Rodgers"),
	array("","","","","Charles & Rebecca Rosenzweig Charitable Foundation ",""),
	array("x","","","","Samuel Ruhmkorff ",""),
	array("","","","","John Russell ",""),
	array("","","","","Neal Sacon '79 and Maureen McClenon Sacon '80 ",""),
	array("x","","","","Hannah Schmidt '99 ",""),
	array("x","","","","Maria Sedova '02 ",""),
	array("","","","","Susan Shapiro ","In honor of Rodney Christopher '86"),
	array("","","","","David and Patricia Sharpe ","In honor of Emily H. Fisher"),
	array("","","","","Patricia M. & H. William Smith, Jr. Foundation",""),
	array("x","","","","Sara Smollett '96 and Karl Krueger '94 ",""),
	array("","","","","Elise S. Sobol '68 ","In honor of the 45th anniversary of the entering class of 1968"),
	array("x","","","","Elizabeth St. John Villard P '01",""),
	array("","","","","Leesa Stanion '75 P '13",""),
	array("","","","","Gael Storck '66 ",""),
	array("","","","","Jonathan Swartz '98 ",""),
	array("","","","","Maryann Tebben ","In honor of Gabriel Asfar, Faculty in French and Arabic"),
	array("","","","","Janet and Malcolm Thompson ",""),
	array("","","","","Jacob Trevick '98 ",""),
	array("","","","","Susanne L. Tunstall '84 ",""),
	array("","","","","Abbie von Schlegell ",""),
	array("","","","","Sandra Walker ","In honor of the Berkshire Festival of Women Writers"),
	array("","","","","Peggy Whitfield ",""),
	array("","","","","Elaine Yee '94 ","In memory of Christine Yee"),
	array("","","","","Asma Abbas and Stephen Hager '04 ",""),
	array("x","","","","Tom '95 and Alana '96 Abott ",""),
	array("","","","","Roberta Klein Ackerman P '82 & '83","In honor of Jennifer Ackerman Kettell '82 and in memory of Leon A. Ackerman"),
	array("","","","","Sameer '00 and Sally Agrawal ",""),
	array("","","","","Tiffany Albright '06 ",""),
	array("x","","","","Jessica Allen '97 ",""),
	array("","","","","Scott Allen '96 ",""),
	array("","","","","Karen and Allen Altman ","In honor of Mike Bergman"),
	array("","","","","A. Barth Anderson '84 ","In honor of Robert Schmidt"),
	array("","","","","Ben Andersen '99 ",""),
	array("","","","","Kurt Anderson '71 ",""),
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous ",""),
	array("","","","","Anonymous ","In memory of Ñacuñán Sáez"),
	array("","","","","Anonymous ","In memory of Noah White Burris '97"),
	array("","","","","Armand Aquino '86 ","In memory of Ñacuñán Sáez"),
	array("","","","","Gabriel Asfar ",""),
	array("","","","","Paul and Elyn Sue Ayers P '92","In honor of Ben Ayers '92"),
	array("","","","","Jeffrey and Mary Ellen Baker P '09",""),
	array("","","","","Loren Becker '95 ",""),
	array("","","","","Robert and Hazel Becker P '95","In honor of Loren Becker '95"),
	array("","","","","Rachel Belanger '06 ","In memory of Carl Kisslinger and Bob and Blanche Belanger"),
	array("","","","","Kyle Bella '06 ",""),
	array("","","","","Marisa Benitez '11 ",""),
	array("","","","","Sandra Benitez P '11",""),
	array("","","","","Mike Bergman ",""),
	array("","","","O","Anna and Ben Bernanke P '00",""),
	array("","","","","Carol J. Bettencourt '77 ",""),
	array("","","","","Alexander Bick '94 and Nealin Parker ",""),
	array("","","","","Ann Billingsley ",""),
	array("x","","","","Marvin R. Birnbaum '79 ","In honor of Perri Brierley-Bowers '08"),
	array("","","","","Brad Bissell '88 ",""),
	array("","","","","Black & Decker Corporation ",""),
	array("","","","","Captain Ronald L. Blake P '88",""),
	array("","","","","John P. Blessington ","In honor of Betty Hall"),
	array("","","","","Benjamin Bogin '91 ",""),
	array("","","","","Michael Sukin and Kim Bonnell P '11",""),
	array("x","","","","Anthony and Ellen Borges P '80 & '87",""),
	array("","","","","Kathryn Boswell ",""),
	array("","","","","Wayne Boswell ",""),
	array("","","","","Michelle Bouche ",""),
	array("","","","","Paul Bowen and Judith Strong P '02",""),
	array("","","","","Rachel Bowen '94 and Delano Lopez '87 ",""),
	array("","","","","Richard Boyd and Karen Twyman P '07","In honor of Emma Boyd '12"),
	array("","","","","David Braslow '02 ",""),
	array("","","","","Elliot Bratton '76 ",""),
	array("","","","","Ann E. Braun '85 ",""),
	array("","","","","Erin Briggerman ",""),
	array("","","","","Morgan Brilliant Smith '79 ","In memory of Leslie R. Sander '83"),
	array("x","","","","Bristol-Myers Squibb Foundation ",""),
	array("","","","","Margaret and Michael Bromberg P '88 & '92","In honor of Simon '92 and Minna '88 Bromberg"),
	array("x","","","","Minna Bromberg '88 ","In honor of the entering class of 1988"),
	array("","","","","Robert R. and Sherry K. Brooks P '88",""),
	array("","","","","Tahira Brooks '94 ",""),
	array("","A","","","Jennifer Browdy '78 P '08","In honor of Nico Hernandez '08"),
	array("","","","","Christopher and Jennifer Browning P '90",""),
	array("","","","","Deb Bunlap ",""),
	array("","","","","Mr. & Mrs. L.J. Burke ","In honor of Emily H. Fisher"),
	array("","","","","Margaret E. Burnett '70 ",""),
	array("x","","","","Chris and Dorothee Callanan ","In honor of Emily H. Fisher"),
	array("","","","","Timothy Cama '04 ",""),
	array("x","","","","Mary Baine Campbell '71 ","In memory of Shelia King '71"),
	array("x","","","","Alida Cantor '01 ","In honor or Alida Cantor '01"),
	array("x","","","","Glenn Cantor and Inge Eriks P '01",""),
	array("","","","","Mary Carswell ",""),
	array("","","","","David and Anna Carvalho P '05","In honor of Christina Anna Carvalho '05"),
	array("","","","","Kathleen Chace Larzelere '67 ",""),
	array("","","","","Jon and Nancy Chalfant-Walker P '00",""),
	array("","","","","Kyle Chao '06 ",""),
	array("","","","","Mary Chase-Ziolek '68 and Keith Chase-Ziolek ",""),
	array("","","","","Linda Chayes P '12","In honor of Victoria Minerva Chayes '12"),
	array("","","","","Bessie Cherry '96 ",""),
	array("","","","","Daniel Chilcoat P '89",""),
	array("x","","","","Ashley Christensen '00 ",""),
	array("x","","","","Rodney Christopher '86 ",""),
	array("","","","","William '88 and Annie Chui ",""),
	array("","","","","Judi and Scott Clippinger P '04",""),
	array("x","","","","Lucy Clippinger '04 ",""),
	array("","","","","Peter and Joan Cocks ",""),
	array("","","","","Chris Coggins and Tanya Kalischer ","In honor of Emily H. Fisher"),
	array("","","","","Alison Colby '76 ","In memory of John Rosenberg '76 and Mark Burkholder '76"),
	array("","","","","Cathy Ann Coley '85 and Andrew Tinari ","In memory of Leslie R. Sander '83"),
	array("","","","","Edna and Jim Collins P '99",""),
	array("","","","","David Collins '99 ",""),
	array("","","","","Computer Associates International ",""),
	array("","","","","Ana-Maria Conley '75 ",""),
	array("","","","","Sharon Conners ",""),
	array("","","","","Margaret and Bradley Cooney P '99",""),
	array("","","","","Kimberley Coppage Rivero '83 ",""),
	array("","","","","Katherine Corn '11 ",""),
	array("","","","","Kim Corn P '11","In memory of Dean Corn"),
	array("x","","","","Joseph Corso, II ",""),
	array("x","","","","Frank and Betty Couvares P '90","In honor of Mary King Austin"),
	array("","","","","Natalie Cowan '09 ","In honor of Nancy Bonvillain and Robert Schmidt"),
	array("","","","","Coleen Cox and Tim Fogarty ","In honor of the students"),
	array("","","","","Paul A. Cox '86 ","In honor of Jeffrey Cua '00"),
	array("x","","","","Elizabeth Cronenwett '93 ",""),
	array("","","","","Caro Crowley '91 and Eric McClenahan ","In memory of Agnes Williams"),
	array("x","","","","Jeffrey Cua '00 ",""),
	array("","","","","Jimmy and Elizabeth Cua P '00",""),
	array("","","","","Irene Cullen Gravina '69 ",""),
	array("","","","","Dana Cummings ",""),
	array("","","","","Ellen and Christopher Curtis ",""),
	array("","","","","Annie Cushman-Kosar ",""),
	array("","","","","Linda M. Darling P '96",""),
	array("","","","","Joan DelPlato ",""),
	array("","","","","Kayla Dickens '12 ",""),
	array("x","","","","Evan Didier '05 ",""),
	array("","","","","Keon Diggs ",""),
	array("x","","","","Debbie and Bob Dillon ",""),
	array("x","","","","John C. Dovel ","In memory of Noah White Burris '97"),
	array("","","","","George & Barbara Dover P '93",""),
	array("","","","","Louis Dow P '13","In honor of Rachel Dow '13"),
	array("","","","","Denise Dufault ",""),
	array("","","","","Bill Dunbar ","In honor of Emily H. Fisher"),
	array("","","","","Thomas Dunlap and Susan Miller P '95",""),
	array("","","","","Jeremy Dunn '81 ",""),
	array("","","","","Robert '00 and Mary Lou Dunton ","In honor of the SRC Younger Scholars Champions Basketball Team"),
	array("","","","","Curran Dwyer '06 ",""),
	array("","","","","John E. Eckart and Karen A. Giannelli P '09","In honor of Andrew Eckart '11"),
	array("","","","","Janet Egelhofer ","In honor of Abbie von Schlegell"),
	array("","","","","Jan Eisenman '68 ","In memory of Vanda Sendzimir '68"),
	array("","","","","Judah Garber and Rebecca Eisenberg P '07",""),
	array("","","","","Erik Elbieh '10 ",""),
	array("","","","","Kari Elsila '90 ",""),
	array("","","","","David Ernst '10 ",""),
	array("","","","","Clara Eusebi '98 ",""),
	array("","","","","Mary Eyring and Richard Newton P '13",""),
	array("","","","","Joshua '92 and Shevah Faber ",""),
	array("","","","","Andrey Falko '05 ",""),
	array("","","","","Valerie Fanarjian ",""),
	array("","","","","Randall Farmer '00 ",""),
	array("","","","","Todd Farrell '00 ","In honor of Thomas and Gail Farrell"),
	array("","","","","Rachel Feltman '08 ","In memory of Jay Embree"),
	array("","","","","Leland and Aline Ferguson P '06","In honor of Sam Ferguson '06"),
	array("x","","","","Shani R. Ferguson '85 and Lionel Artom-Ginzburg '88 ",""),
	array("","","","","Kayne Ferrier P '94",""),
	array("x","","","","John and Zirka Filipczak P '96",""),
	array("","","","","Peter Filkins ","In honor of Emily H. Fisher"),
	array("","","","","Christopher M. Fink P '07","In honor of Charles Fink '07"),
	array("","","","","Fischer Orthodontics ","In honor of Ethan Ackelsberg '12"),
	array("","","","","Rebecca Fiske and Deane Zarvis P '98 & '07 ",""),
	array("","","","","Katherine Fleming '94 ",""),
	array("","","","","Stephan Fowlkes '88 ",""),
	array("x","","","","Kathryn Friedman '02 ",""),
	array("x","","","","Mary Martin Gant P '99","In honor of Jason Martin Snell's 13th Birthday"),
	array("","A","","","Hillary Gardner '02 ",""),
	array("","","","","Ashleigh Garvey '01 ",""),
	array("","","","","Leila H. Gary '93 ",""),
	array("","","","","Wendy Clarissa Geiger '80 ","In memory of Caleb Roosevelt '79"),
	array("","","","","Lisa Gelfand P '01",""),
	array("","","","","Elaine Gerst ",""),
	array("","","","","Jacob Gerstein '01 ",""),
	array("x","","","","Nat Gertler '79 ",""),
	array("","","","","Matthew Getch '11 ",""),
	array("","","","","Janice Gildawie ",""),
	array("x","","","","Beri Gilfix P '88",""),
	array("","","","","Dragan Gill '02 ",""),
	array("x","","","","Leonard and Nansi Glick P '89","In honor of Leutitia Swayze Mahood"),
	array("","","","","Susan Golden '78 ",""),
	array("","","","","Julia Goode and Robert Sadowsky P '12",""),
	array("x","","","","Wendy Goodman '67 ","In honor of Miss Young"),
	array("","","","","Google ",""),
	array("","","","","Johanna Gosse '01 ","In honor of Professor Barbara Resnik"),
	array("","","","","Reisa Gould-Donath P '90",""),
	array("","","","","Christopher Lee Grace '05 ","In honor of current and future Rockers"),
	array("","","","","Andrea Grayson '80 ","In honor of the Art Department"),
	array("","","","","Zachary Green '99 ","In memory of Will Friedman '99"),
	array("","","","","Susan Grieder P '07",""),
	array("","","","","Zoe Grieder '07 ",""),
	array("x","","","","Barry and Joanna Groebel P '05",""),
	array("","","","","Martha Groet ",""),
	array("","","","","Sarah Grossman Lewis '73 ",""),
	array("x","","","","Chris and Diane Gruber P '93",""),
	array("","","","","Melanie Guerin ",""),
	array("x","","","","Cara E. Haas '92 ",""),
	array("","","","","Elizabeth M. Hall P '00",""),
	array("","","","","Dr. Thomas Hall and Elizabeth McLoughlin ",""),
	array("","","","","Dr. Jennifer Halpern P '12","In honor of Zev Vel '12"),
	array("","","","","Miranda Hambro '87 ",""),
	array("x","","","","Maudie Hampden Shah '99 and Sumul Shah '99","In honor of Barbara & Ed Hampden and Mahendra & Shobhana Shah"),
	array("","","","","Lily L. Han '99 ",""),
	array("","","","","Allyn Harcus '88 ",""),
	array("","","","","Harvard Community Gifts ",""),
	array("x","","","","Kathy and Joe Hatfield P '89",""),
	array("","","","","Gary and Linda Hauze P '00","In honor of Andrew Hauze '00"),
	array("","","","","Eden-Renee Hayes ",""),
	array("","","","","Anthony Mark Hecht P '10","In memory of Sidney Robert Hecht and Zanetta Hecht"),
	array("","","","","Leslye Heilig and Lou Davis ",""),
	array("","","","","James Lucas Hepokoski '01 ",""),
	array("","","","","Terri Herubin P '12","In memory of John Pandolfi"),
	array("","","","","Kevin and Ana Marie Higgins Ttee ",""),
	array("","","","","Thomas Hitchins and Shelly Shapiro P '07",""),
	array("","","","","Hal L. Holladay ",""),
	array("","","","","Elizabeth Hoogs '97 ",""),
	array("","","","","Elizabeth Horan '73 and Paul Skilton ",""),
	array("","","","","Phillip Howell ","In honor of David Lovely '96 and James Lai"),
	array("","","","","C. Linda Howitt P '96","In honor of Emry de St. Andre"),
	array("","","","","Aaron Hurwitz '99 and Laura Selkirk '98 ",""),
	array("","","","","Jamie Hutchinson ","In memory of Natalie Harper"),
	array("x","","","","Mary Jo Hutchison P '88 and Emmette R. Hutchison '98",""),
	array("","","","","Adam Huttler ",""),
	array("","","","","Francis and Harriet Iglehart P '69",""),
	array("","","","","Valerie Ingram P '04",""),
	array("x","","","","Julia A. Insinger '77 ",""),
	array("","","","","Shahzad Ismaily '88 ","In honor of Wazir Ismaily"),
	array("","","","","David K. Jacke '76 ",""),
	array("","","","","Tisha Jepson Fang '82 ",""),
	array("","","","","Sarah Jimenez '06 ",""),
	array("","","","","Rosanne Johnson P '11","In honor of Coriana Johnson '11"),
	array("","","","","Ms. Rebecca Jones '01 ",""),
	array("","","","","Paula Junn '02 ",""),
	array("","","","","Karen Juster Hecht P '10","In honor of Izaak Mark Hecht '10"),
	array("","","","","Benjamin Kalish '98 ",""),
	array("x","","","","Bryna Kamel Blaine P '90","In honor of Darian S. Blaine '90"),
	array("","","","","William Taylor Kang '09 ",""),
	array("","","","","Micki Kaufman '85 ",""),
	array("","","","","Aileen Kawabe '93 ","In memory of Galen Gibson '90 and Ñacuñán Sáez"),
	array("","","","","Lori Kenepp '81 ",""),
	array("","","","","Laura Kessel '05 ",""),
	array("","","","","Jennifer Ackerman Kettell '82 ",""),
	array("","","","","Judith Kiely ",""),
	array("","","","","Erica Kiesewetter P '07 & '12",""),
	array("x","","","","Marie (Mimi) Kittredge '75 and Clark Broida ",""),
	array("x","","","","Richard Kittredge and Tanya Korelsky P '00",""),
	array("","","","","Peter Knapp '80 and Rob Gates ",""),
	array("","","","","Michael P. Koch '74 ",""),
	array("","","","","Sharon and Stephen Koons P '08",""),
	array("","","","","Eric Kramer ",""),
	array("","","","","Peter Kramer ","In honor of Rodney Christopher '86"),
	array("","","","","Cathie and Gary Krellenstein P '08","In honor of James Krellenstein '08"),
	array("","","","","Ellen Condliffe Lagemann ",""),
	array("","","","","Daniel Landau '89 ",""),
	array("","","","","Joy Lapseritis '90 ",""),
	array("","","","","Alexis and Philip Lavine P '98","In honor of Amy Lavine '98"),
	array("x","","","","Michael Leahy and M. B. Maughan P '04",""),
	array("","","","","April Lee '01 ",""),
	array("","","","","James and Kelly Lee P '12",""),
	array("","","","","Cindy Lehmbeck Wood '78 ",""),
	array("","","","","Joan LeLacheur '73 ",""),
	array("x","","","","Elizabeth Lester P '85",""),
	array("x","","","","Barbara Letton '97 ",""),
	array("","","","","Andrew Levine '97 ",""),
	array("x","","","","David P. Levine '98 ",""),
	array("","","","","Carol Lewis and Patricia De Angelis P '07",""),
	array("","","","","Sianna Lieb Hannah '85 ","In honor of Jim Monsonis"),
	array("","","","","Leslie Lieberman P '99","In honor of Stephen Todd Lieberman '03"),
	array("","","","","Liz Lierman ",""),
	array("","","","","Peter and Evelyn Liffiton P '97",""),
	array("","","","","Jacqueline Smith Littlejohn '71 ",""),
	array("x","","","","Sarah '01 and Michael LoCascio ",""),
	array("","","","","Karen and John Loeser P '02",""),
	array("","","","","Deborah F. Loomis '68 ",""),
	array("","","","","Ann Lynnworth '80 ",""),
	array("","","","","Larry and Elaine Lynnworth P '80",""),
	array("","","","","Sue Lyon ",""),
	array("x","","","","Jodie Dejio Maisfehlt '00 ",""),
	array("","","","","Dr. Ron Majdalany, V.M.D., Seekonk Veterinary Hospital",""),
	array("","","","","Samia Makar '77 ",""),
	array("","","","","Lisa B. Martin '76 ","In honor of future outstanding alumni"),
	array("x","","","","Michael Martin '89 ",""),
	array("","","","","Lawrence Masland and Pamela Talbot ","In memory of Todd Lincoln Tisdale '88"),
	array("x","","","","Maya Matheis '03 ","In honor of Anne O'Dwyer"),
	array("","","","","Brendan Mathews and Margaret Keller","In honor of Emily H. Fisher"),
	array("","","","","Tansy Mathisen '03 ",""),
	array("","","","","Michael Mauel P '10","In honor of Avery Mauel '10"),
	array("x","","","","Nang Hlaing Tin Maung '01 ","In honor of Emily H. Fisher"),
	array("","","","","Caroline Mayhew '02 ",""),
	array("","","","","Amelia Maynard '99 ",""),
	array("x","","","","Robert W. Maynard and Susan Sullivan Maynard P '89 & '99","In honor of Adrienne '89 and Amelia '99 Maynard"),
	array("","","","","Daphne Mazuz '01 ",""),
	array("","","","","Carole McCauley ",""),
	array("","","","","Steve and Chris McClelland P '97 & '00",""),
	array("","","","","Mac '78 and Donna McClurkan ",""),
	array("","","","","Amanda McCormick '93 ",""),
	array("x","","","","Robert '81 and Jennifer McCue ",""),
	array("","","","","Darcy McCusker '06 ",""),
	array("","","","","Caitlin McDonald '01 ",""),
	array("","","","","Tom McElderry '89 ","In memory of Ñacuñán Sáez"),
	array("","","","","Sally McGregor P '10",""),
	array("","","","","Sylvia McIntosh P '12",""),
	array("","","","","Margaret McKee '97 ",""),
	array("","","","","C. Ross and Christina McKenrick P '02",""),
	array("","","","","Tom and Susanna Meade Schindler '69 P '06",""),
	array("","","","","Miriam Melnick '08 ",""),
	array("","","","","Jean B. Meyers P '83",""),
	array("","","","","Nancy Friday '83 and Mark Miller '83 ","In honor of Jim Monsonis and Lenore Gensburg '78"),
	array("","","","","Allison Moore P '10","In honor of Avery Grace Mauel '10"),
	array("","","","","Stephen and Kimberly Moore P '02",""),
	array("","","","","Nancy Morgan ",""),
	array("","","","","Susan Mower ",""),
	array("","","","","Wendy Mueller '85 ",""),
	array("","","","","Lynn Mulheron '86 ",""),
	array("x","","","","Josh Muskovitz '82 and Marley Mills '84 ",""),
	array("","","","","Ingyin Hla Myint '06 ","In honor of Emily H. Fisher"),
	array("","","","","My Versatile Secretary ",""),
	array("","","","","Paul and Tamami Naamon ",""),
	array("x","","","","James Nadeau '81 and Jill Mandell '83 ",""),
	array("","","","","Doug Nannen '75 ","In memory of Peter Treistman '75"),
	array("","","","","Judith Nardacci ",""),
	array("x","","","","Sarah C. Nash '83 ",""),
	array("","","","","Saket Navlakha '00 ","In memory of Lauren Webster '02"),
	array("","","","","Thomas Neely and Debbie Silverblank P '06","In honor of Dylan Neely '02"),
	array("","","","","Hannah Neidorf '00 ",""),
	array("","","","","Nancy Nirenberg ","In honor of Vera Kalm"),
	array("","","","","Guy and Liane Nouri P '12","In honor of Edmond and Gloria Nouri"),
	array("","","","","Su Hlaing Win Nu '05 ","In honor of Emily H. Fisher"),
	array("","","","","Phyu Hninn Nyein '05 ","In honor of Emily H. Fisher"),
	array("","","","","Erin M. Oakley '95 and Samuel Scalfano ",""),
	array("","","","","Kirsten Trabbic Olson '88 Ph.D. ","In memory of Patrick Brooks '88"),
	array("","","","","Dennis and Susan O'Neil P '10",""),
	array("x","","","","Ada Palmer '97 ",""),
	array("","","","","Heidi Parsons '80 ","In memory of Adams Douglas '72"),
	array("","","","","Keith Pelczarski '87 ",""),
	array("x","","","","Benjamin Pender-Cudlip '01 ",""),
	array("x","","","","John C. Pender-Cudlip P '01","In honor of Ben Pender-Cudlip '01"),
	array("","","","","David Pepper '88 and Jennifer Ferrara ",""),
	array("","","","","Nessa and Robert Peters P '98",""),
	array("","","","","Katherine Pichard P '13",""),
	array("","","","","Chantal Pinard '01 ",""),
	array("","","","","Kelly Pitts '93 ",""),
	array("","","","","Perri Pivovar '86 ",""),
	array("","","","","Ruthe Ponturo ",""),
	array("","","","","Adriane Powell ","In memory of Jane Rodgers"),
	array("","","","","Charles Powell '09 ",""),
	array("","","","","Abby Pratt ",""),
	array("x","","","","Howard and Ellen Pritham P '86",""),
	array("","","","","Serban and Orel Protopopescu P '94",""),
	array("","","","","Evan and Sandra Prytherch P '12","In memory of Joan Prytherch"),
	array("x","","","","Gretchen Pulver '75 ",""),
	array("x","","","","Fran and Spence Putnam P '97","In honor of Chris Putnam-Pouliot '97"),
	array("","","","","Elizabeth Putnam Stowe '71 and Maynard Stowe",""),
	array("","","","","Eduardo Quiroz '90 ",""),
	array("","","","","Lauren Randall-Myers '05 ",""),
	array("","","","","Ingrid Rasmussen ","In honor of Rodney Christopher '86"),
	array("x","","","","Belinda Rathbone '66 ",""),
	array("","","","","William Redding '94 ",""),
	array("","","","","Ann Reid '75 ",""),
	array("","","","","Laura & Bruce Reid P '12",""),
	array("x","","","","Diane Rhoades-Warner ","In memory of Greg Rhoades"),
	array("","","","","David and Judy Rimple P '80","In memory of Nancy A. Rimple '80"),
	array("","","","","Don and Elaine Ritchie P '82 & '84 ",""),
	array("","","","","Deanna Rivkin '10 ","In honor of Catalina Island students"),
	array("x","","","","C. Lee Rogers ",""),
	array("","","","","Vikki Rogers '91 ",""),
	array("","","","","Daniel Romanow ",""),
	array("","","","","Heidi and Sheldon Rothberg P '06",""),
	array("","","","","Natanah Rothberg '06 ",""),
	array("","","","","Sandra Rowland-Hack and Steven Hack P '01","In honor of Sarah Hack '01"),
	array("","","","","Mira Rubens and Peter Landy P '10",""),
	array("","","","","Harold and Roberta Rudin P '84","In memory of Derek Gross '84"),
	array("","","","","Jenny Russell ","In honor of Judith and Ba Win"),
	array("","","","","Melinda Russell '79 ",""),
	array("","","","","Beth Sack and Stephan Green",""),
	array("x","","","","Gabe Salgado '05 ",""),
	array("x","","","","Barbara and Evan Salop P '01","In honor of Michael Nash '06"),
	array("x","","","","Craig Sauer '90 ",""),
	array("","","","","W. Eric Sauerhoefer '89 ","In honor of Colette van Kerckvoorde"),
	array("","","","","Marcia A. Savage P '98",""),
	array("","","","","Robin Scanlon P '09",""),
	array("","","","","Catherine '80 and Monk Schane-Lydon ",""),
	array("x","","","","Andrew and Karen Schwartz P '96","In honor of Peter '96 and Kaia '93 Schwartz"),
	array("x","","","","Aurelia C. Scott '73 ",""),
	array("","","","","Hilary S.L. Scott '79 and Gretchen Wehrle-Scott ",""),
	array("","","","","Louise '66 and Caleb Scott ",""),
	array("","","","","The Reverend Will Scott '96 & Matt Chayt ","In honor of Rodney Christopher '86"),
	array("","","","","David Segil '00 ",""),
	array("","","","","Robert and Elizabeth Seidel P '74",""),
	array("","","","","Anne M. Serafin ","In honor of Jenny Browdy de Hernandez '78"),
	array("x","","","","Allyson Sgro '01 and Bjorn-Erik Townsend '94 ",""),
	array("","","","","Diane and Bari Shamas P '12",""),
	array("","","","","Hilda Shapiro ",""),
	array("x","","","","Zoe Sherman '95 ",""),
	array("","","","","Gennady Shmukler P '93","In honor of Evelina Shmukler '95"),
	array("","","","","Nate Shoobs 12 ",""),
	array("x","","","","Tim '82 and Myriam Siftar ",""),
	array("","","","","Molly True Simpson '03 ",""),
	array("x","","","","Christopher Sink and Jon A. MacClaren",""),
	array("","","","","Matthew Siroka '88 ",""),
	array("","","","","Davis Skeist and Rebecca Henderson ",""),
	array("x","","","","Roxann Slate '03 ",""),
	array("x","","","","Seymour and Zoya Slive P '67",""),
	array("","","","","Alexandra Smith '08 ",""),
	array("","","","","Brian Joseph Smith '04 ",""),
	array("","","","","George T. Smith ",""),
	array("","","","","Lauren Smith ","In honor of Patty Dooley"),
	array("","","","","Tom and Sherrye Smith P '08",""),
	array("","","","","Linda Smothers and Richard Gregg P '11","In honor of Harrison Gregg '11"),
	array("","","","","Robert L. Snyder ",""),
	array("x","","","","Cindy J. Speaker '81 ",""),
	array("","","","","David '81 and Janis Spivack ",""),
	array("","","","","Philip B. Spivey ","In honor of Rodney Christopher '86"),
	array("x","","","","Erica Spizz '94 ",""),
	array("","","","","Anna Stahlnecker '99 ",""),
	array("","","","","Jan Staller '70 ",""),
	array("","","","","Camelia Stan '03 ",""),
	array("","","","","Morey Stettner ",""),
	array("x","","","","Mary M. Stiles '87 ",""),
	array("","","","","Kate St. John Villard-Howe '01 ",""),
	array("","","","","David Stone and Susan Gutwill P '11","In honor of Liza Mei Stone '11"),
	array("","","","","Alicia Stube '04 ",""),
	array("","","","","Adrienne Sussman '03 ",""),
	array("","","","","Andrew and Sally Sussman P '03","In honor of Adrienne Sussman '03"),
	array("x","","","","Stephanie '00 and Frank Swales Scalambrino ",""),
	array("","","","","Michael and Pat Swartz P '98",""),
	array("","","","","Carl and Elizabeth Sword P '77",""),
	array("","","","","Peter Sword '77 ",""),
	array("","","","","Joanna and Edward Szwyd P '09",""),
	array("","","","","Carol Taylor and Dennis Norman P '02",""),
	array("","","","","John '76 and Sonya Thompson ",""),
	array("","","","","Marc Thompson '86 ",""),
	array("","","","","Bill Tipper '73 ",""),
	array("","","","","Peter Tiso '02 ","In memory of Tom Coote's ponytail"),
	array("","","","","Kris Tromiczak '76 ",""),
	array("","","","","J. Craig and Sue Trouwborst P '91","In memory of Galen Gibson '90"),
	array("x","","","","Elizabeth Tuggey Lynch '02 and Ryan Lynch ",""),
	array("","","","","UBS Matching Gift Program ",""),
	array("","","","","Rashad Ullah '95 ",""),
	array("","","","","Summer Unsinn '96 ","In memory of Hendrik Doorn '96"),
	array("","","","","Colette van Kerckvoorde ",""),
	array("","","","","Louise Vasilakos and Daniel Goure P '02",""),
	array("","","","","Carmen Vendelin P '06","In honor of Stan Jonasson and Linda Jangaard"),
	array("","","","","Melissa Vorhies Roske '90 ","In honor of Edward Roske '90"),
	array("","","","","Betsy Walker '68 ",""),
	array("","","","","Wayne Wang P '92",""),
	array("x","","","","Marvin Wasserman and Barbara von Bulow P '02","In honor of Matthew Wasserman '02"),
	array("","","","","Clifford Wattley and Nancy Griffin P '05",""),
	array("","","","","Diana and Robert Weggler P '12","In honor of Pearl Weggler '12"),
	array("","","","","David Weill P '12",""),
	array("","","","","Francine Weinberg ",""),
	array("","","","","David and Sandra Welsh P '98",""),
	array("","","","","Francis Whitesell '04 ",""),
	array("","","","","Kelly Wickliff ","In honor of Brittany Wickliff"),
	array("","","","","C.C. Wiegand '93 ",""),
	array("","","","","Brook Wiers '84 ","In memory of Heather Hawley '84"),
	array("x","","","","Jay and Hermine Williams P '84",""),
	array("","","","","Sarah E. Williams '78 ",""),
	array("","","","","Zaw Win '92 ","In honor of Emily H. Fisher"),
	array("","","","","Matthew Winkler '89 ",""),
	array("","","","","Jeremy Wolf '96 ",""),
	array("","","","","Patricia L. Wolf P '76","In honor of Sharon M. Wolf Beck '76"),
	array("","","","","Anna Wolk '98 ",""),
	array("x","","","","David and Robin Wood P '92","In honor of Simon's Rock faculty"),
	array("","","","","Sarah Wright '80 ",""),
	array("x","","","","Li Liang Xu and Yan Wei Guo P '08",""),
	array("","","","","Michael Xu '08 ",""),
	array("","","","","Nancy Yanoshak ",""),
	array("x","","","","Kwok and Gee Ying Kip P '93",""),
	array("","","","","Adrienne York-Minor '95 ",""),
	array("","","","","Gail Young ","In memory of Monse Selosse Young and Isabel Selosse Russell"),
	array("","","","","Kenneth G. Young '90 ",""),
	array("","","","","Robert Young '98 ",""),
	array("","","","","Charlotte Zinsser Booth '69 ",""));
$donorsinkind = array(
	array("","","","","David Basler and Cyd Melcher P '10",""),
	array("","","","","Seth and Victoria Black P '10",""),
	array("","","","","Wesley Brown ",""),
	array("","","","","Daniel Cassidy and Linda Michel-Cassidy P '12",""),
	array("","","","","Nancy and Ted Cobden ",""),
	array("","","","","Uneeda and Sola Collins P '11",""),
	array("x","","","","Patty Dooley ",""),
	array("","","","","Peter Elliston ",""),
	array("","","","","Joan Goodkind ",""),
	array("","","","","Jim Hansen ",""),
	array("","","","","Donald and Kristine Hill P '06 & '11",""),
	array("","","","","Bruce and Marianne MacCullagh P '09",""),
	array("","","","","Nancy Magnusson ",""),
	array("","","","","Betsy McTiernan ",""),
	array("","","","","Gregory Meeh and Hillary Nelson ",""),
	array("","","","","Michael and Carole Paquette P '11",""),
	array("","","","","Norman Schnayer ",""),
	array("","","","","Gillian Shallcross ",""),
	array("","","","","Gabriella Spitz '07 ",""),
	array("","","","","Bobby and Geraldine Welch P '12",""));
	
$donorArrays = array("donors100" => $donors100, "donors2599" => $donors2599, "donors1524" => $donors1524, 
					 "donors1014" => $donors1014, "donors59" => $donors59, "donors14" => $donors14,
					 "donors5009999" => $donors5009999, "donors250499" => $donors250499, "donorsinkind" => $donorsinkind);

// $25,000-$99,999
$donors100Header = '<a name="100k" id="100k"></a>$100,000 and above';
$donors2599Header = '<a name="25k" id="25k"></a>$25,000-$99,999';
$donors1524Header = '<a name="15k" id="15k"></a>$15,000-$24,999';
$donors1014Header = '<a name="10k" id="10k"></a>$10,000-$14,999';
$donors59Header = '<a name="5k" id="5k"></a>$5,000-$9,999';
$donors14Header = '<a name="1000" id="1000"></a>$1,000-$2,499';
$donors5009999Header  = '<a name="500" id="500"></a>$500-$999';
$donors250499Header = '<a name="250" id="250"></a>$250-$499';
$donorsinkindHeader = '<a name="inkind" id="inkind"></a>Gifts in Kind';

$html = "";
foreach($donorArrays as $donorArrayKey => $donorArrayArray){
	
 //<span class="key">O</span><span style="padding: 3px 0px 3px 2px; width: 23px" class="key"><img width="13" height="20" src="/images-1/mini-sapling.png" style="margin-right: 2px !important" alt="" /></span><span style="width: 300px" class="undrln">Margaret Kendrick Blodgett Foundation</span><br style="clear: both" />
  $x = 0;
  $lColSet = false;
  $rColSet = false;
  foreach($donorArrayArray as $donorArray){
	$header  = "";
	$header .= $donorArrayKey."Header";
	
	$howMany = count($donorArrayArray);
	if ( ($howMany/2) >= $x && !$lColSet) { // left column
		$html .= '<div id="cntnr"><div id="LCol"><p><span class="bld">'.$$header.'</span><br style="clear: both" />';
		$lColSet = true;
	}
	if ( ($howMany/2) < $x && !$rColSet) { // left column
		$html .= '</div><div id="RCol"><p><br />';
		$rColSet = true;
	}
	$width = 300;
	
	// part 2
	if($donorArray[1] != ""){
		$html .= '<span class="key" style="margin-right: 6px">';
		$html .= $donorArray[1];
		$html .= '</span>';
		$width = $width-25;
	}
	else {
		$html .= '<span class="key">';
		$html .= '</span>';
	}
	
	// part 3
	if($donorArray[2] != ""){
		$html .= '<span class="key" style="margin-right: 6px">';
		$html .= $donorArray[2];
		$html .= '</span>';
		$width = $width-25;
	}
	else {
		$html .= '<span class="key">';
		$html .= '</span>';
	}

	// part 4
	if($donorArray[3] != ""){
		$html .= '<span class="key" style="margin-right: 6px">';
		$html .= $donorArray[3];
		$html .= '</span>';
	}
	else {
		$html .= '<span class="key">';
		$html .= '</span>';
	}

	// part 1, sapling
	if($donorArray[0] != ""){
		$html .= '<span style="padding: 3px 0px 3px 2px; width: 23px" class="key"><img width="13" height="20" src="/images-1/mini-sapling.png" style="margin-right: 2px !important" alt="" /></span>';
		if($width > 250){
			$width = $width-25;
		}
	}	
	// part 5
	if($donorArray[4] != ""){
		$html .= '<span style="font-size: 14px; width: '.$width.'px" class="undrln">';
		$html .= $donorArray[4];
		if($donorArray[5] != ""){
			$html .= '<br style="clear: both" /><span style="font-size: 14px; font-style: italic; padding-left: 25px;">';
			$html .= $donorArray[5];
			$html .= '</span>';
		}
		$html .= '</span>';
	}
	// part 6
	// <br style="clear: both" /> if empty, prepend  with <br /> if not
	$html .= '<div style="padding-top: 7px; clear: both"  /></div>';
	$x++;
  }
  $html .="<p>&nbsp;</p></div></div>";


}
echo '<p><strong>Key</strong></p>
<p><span class="undrln" style="width: 700px"><span class="key" style="width: 14px;">O</span>Member of the Board of Overseers or an Overseer-Affiliated Foundation</span><br style="clear: both" />
<span class="undrln" style="width: 700px"><span class="key" style="width: 14px;">A</span>Member of the Alumni Leadership Council</span><br style="clear: both" />
<span class="undrln" style="width: 700px"><span class="key" style="width: 14px;">P</span>Member of the Parent Leadership Council</span><br style="clear: both" />
<span class="undrln" style="width: 700px"><span style="padding: 3px 0px 3px 2px; width: 23px" class="key"><img width="13" height="20" src="/images-1/mini-sapling.png" style="margin-right: 2px !important" alt="" /></span>The Sapling Society identifies those loyal donors who have given consecutively in the previous five or more years.</span></p>
<div style="clear: both; height: 10px">&nbsp;</div>
<div id="cntnr">
<div id="LCol">
<p><a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#100k">$100,000 and greater</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#25k">$25,000 - $99,999</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#15k">$15,000 - $24,999</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#10k">$10,000 - $14,999</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#5k">$5,000 - $9,999</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#2500">$2,500 - $4,999</a></p>
<p>&nbsp;</p>
</div>
<div id="RCol">
<p><a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#1000">$1,000 - $2,499</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#500">$500 - $999</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#250">$250 - $499</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#1">$1 - $249</a><br />
<a class="style1" href="http://www.simons-rock.edu/donate/donors-2012/#inkind">Gifts in Kind</a></p>
</div>
</div>';
echo $html;

?>









